name: predictive_maintenance_env
channels:
  - defaults
dependencies:
  - python=3.9
  - scikit-learn=1.0.2
  - numpy=1.21.5
  - pandas=1.4.2
  - pip
  - pip:
      - mlflow==2.3.2
      - matplotlib==3.5.1
